# Generated by Django 5.0.6 on 2024-08-18 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_user',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Professional_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
