# Generated by Django 5.0.6 on 2024-08-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0002_professional_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('HAIRDRESSING', 'Hairdressing'), ('BARBER', 'Barber'), ('COSMETOLOGY', 'Cosmetology'), ('MANICURE_PEDICURE', 'Manicure and Pedicure'), ('MASSAGES', 'Massages'), ('HAIR_REMOVAL', 'Hair Removal'), ('MAKEUP', 'Makeup'), ('AESTHETIC_MEDICINE', 'Aesthetic Medicine'), ('PERSONAL_TRAINING', 'Personal Training'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('TATTOOS_PIERCING', 'Tattoos and Piercing'), ('SPRAY_TANNING', 'Spray Tanning'), ('EYELASH_STYLING', 'Eyelash Styling'), ('EYEBROW_STYLING', 'Eyebrow Styling'), ('DIETETICS', 'Dietetics'), ('SPA_RELAXATION', 'Spa and Relaxation'), ('FACIAL_TREATMENTS', 'Facial Treatments'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_created_by', to='bookit.professional_user')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookit.service')),
            ],
        ),
    ]
