# Generated by Django 5.0.6 on 2024-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0004_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
