# Generated by Django 5.0.6 on 2024-08-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0006_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='bookit.service'),
            preserve_default=False,
        ),
    ]
