# Generated by Django 5.0.6 on 2024-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0007_availability_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All of Week', 'All of Week')], max_length=11),
        ),
    ]
