# Generated by Django 5.0.6 on 2024-08-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0008_alter_availability_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
    ]
