# Generated by Django 5.0.6 on 2024-08-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookit', '0009_remove_availability_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional_user',
            old_name='url',
            new_name='company_logo',
        ),
    ]
