# Generated by Django 5.0.4 on 2024-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
