# Generated by Django 5.0.4 on 2024-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_bids_bid_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home & Garden', 'Home & Garden'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Helalth & Beauty', 'Health & Beauty'), ('Collectibles & Art', 'Collectibles & Art'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Automotive', 'Automotive'), ('Jewelry & Watches', 'Jewelry & Watches')], default='Fashion', max_length=50),
        ),
    ]
