# Generated by Django 5.0.4 on 2024-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
