# Generated by Django 5.0.4 on 2024-06-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_timestamp_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folowers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
