# Generated by Django 5.0.4 on 2024-06-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_folowers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folowers',
            new_name='Follower',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='folower',
            new_name='follower',
        ),
    ]
