# Generated by Django 5.0.4 on 2024-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='if_like',
            field=models.BooleanField(default=True),
        ),
    ]
